<?php

/**
 * @file
 * drupal.org specific verification helpers for the project packaging system.
 *
 * This module was written to provide drupal.org-specific validation
 * functions for .make files used on drupal.org, and it would most likely
 * require some custom hacking to work in any other environment.
 */

// -------------------
// BEGIN CONFIGURATION
// -------------------

// The term ID that a release node must have in order to require verification.
define('PROJECT_VERIFY_PACKAGE_PROJECT_TYPE_TID', 96);

// NOTE: Other configuration settings need to be defined at the top of the
// project_verify_package.pages.inc file.

// -----------------
// END CONFIGURATION
// -----------------

/**
 * Implement hook_form_alter().
 */
function project_verify_package_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'project_release_node_form':
      // Can't conditionally add the validation to the final release form,
      // as the form is cached and we don't get back to the alter hook. So,
      // just always add the validator and check for the final form there.
      $form['#validate'][] = 'project_verify_package_verify_release_node';
      break;
  }
}

/**
 * Verify if a drupal-cxorg.make file in a release has the right format.
 *
 * This function must be included in the main module file, as hook_form_alter()
 * is not called on cached forms. It's provided here as a simple wrapper for
 * the internal validation function.
 */
function project_verify_package_verify_release_node($form, &$form_state) {
  require_once(drupal_get_path('module', 'project_verify_package') . '/project_verify_package.pages.inc');
  _project_verify_package_verify_release_node($form, $form_state);
}
