<?php

/**
* @file
* Install functions for project_verify_package module.
*/

function project_verify_package_enable() {
  // Make this module heavier than project_release module.
  $weight = db_query("SELECT weight FROM {system} WHERE name = 'project_release'")->fetchField();
  db_update('system')
    ->fields(array('weight' => $weight + 1))
    ->condition('name', 'project_verify_package')
    ->execute();
}
