<?php
// $Id$

/**
 * @file
 * This module contains customizations used on drupal.org itself. It is not
 * meant to be useful for other sites, except as an example of the kinds of
 * modifications you can make with a site-specific module.
 */


/// Release node ids for issues we're currently tracking (Drupal 7).
define('ISSUE_RIDS', '156281');
define('DRUPALORG_CVS_USER_ROLE', 8);

/**
 * Implementation of hook_cron().
 */
function drupalorg_cron() {
  drupalorg_issue_counts();
}

/**
 * Pulls issue counts for various issue queues on drupal.org.
 */
function drupalorg_issue_counts() {
  $issue_counts['Pending bugs'] = db_result(db_query("SELECT COUNT(*) FROM {project_issues} pi INNER JOIN {node} n ON pi.nid = n.nid WHERE n.status = 1 AND  pid = 3060 AND category = 'bug' AND sid = 1 AND priority IN (1,2) AND rid IN (". ISSUE_RIDS .")"));
  $issue_counts['Critical issues'] = db_result(db_query("SELECT COUNT(*) FROM {project_issues} pi INNER JOIN {node} n ON pi.nid = n.nid WHERE n.status = 1 AND  pid = 3060 AND category IN ('bug', 'task') AND sid IN (1,8,13,14) AND priority = 1 AND rid IN (". ISSUE_RIDS .")"));
  $issue_counts['Patch queue'] = db_result(db_query("SELECT COUNT(*) FROM {project_issues} pi INNER JOIN {node} n ON pi.nid = n.nid WHERE n.status = 1 AND  pid = 3060 AND sid IN (8,13,14) AND rid IN (". ISSUE_RIDS .")"));
  $issue_counts['Patches to review'] = db_result(db_query("SELECT COUNT(*) FROM {project_issues} pi INNER JOIN {node} n ON pi.nid = n.nid WHERE n.status = 1 AND  pid = 3060 AND sid IN (8) AND rid IN (". ISSUE_RIDS .")"));
  variable_set('drupalorg_issue_counts', $issue_counts);
}


/**
 * Implementation of hook_form_alter().
 */
function drupalorg_form_alter($form_id, &$form) {
  // List of forms to check for overrides, and the corresponding permissions.
  $override_forms = array(
    'book_node_form' => 'edit book pages',
    'forum_node_form' => 'administer nodes',
    'page_node_form' => 'administer nodes',
    'simplenews_node_form' => 'create newsletter',
    'story_node_form' => 'administer nodes',
  );
  // Override the access for attachments if it's a forbidden form,
  // and the user does not have sufficient permissions.
  if (in_array($form_id, array_keys($override_forms)) && !user_access($override_forms[$form_id])) {
    if (isset($form['attachments']['#access'])) {
      $form['attachments']['#access'] = FALSE;
    }
  }

  // Make the "Issue tags" vocabulary not so prominent on issue nodes.
  if ($form_id == 'project_issue_node_form') {
    $form['taxonomy']['#type'] = 'fieldset';
    $form['taxonomy']['#title'] = t('Categories');
    $form['taxonomy']['#collapsible'] = TRUE;
    $form['taxonomy']['#collapsed'] = TRUE;
    $form['taxonomy']['#weight'] = 35;
  }
  else if ($form_id == 'cvs_user_edit_form') {
    $submit['drupalorg_cvs_user_edit_submit'] = array();
    $form['#submit'] = $form['#submit'] + $submit;
  }
}

/**
 * Implementation of hook_comment.
 */
function drupalorg_comment(&$comment, $op) {
  switch ($op) {
    case 'insert':
    case 'update':
      $_SESSION['not_slavesafe'] = TRUE;
      break;
  }
}

function drupalorg_cvs_user_edit_submit($form_id, &$form_values) {
  if (isset($form_values['cvs_status'])) {
    switch ($form_values['cvs_status']) {
      case CVS_APPROVED:
        db_query('INSERT INTO {users_roles} (uid, rid) VALUES (%d, %d)', $form_values['cvs_uid'], DRUPALORG_CVS_USER_ROLE);
        break;
      case CVS_DISABLED:
        db_query('DELETE FROM {users_roles} WHERE uid = %d AND rid = %d', $form_values['cvs_uid'], DRUPALORG_CVS_USER_ROLE);
        break;
    }
    global $locale;
    cache_clear_all($form_values['cvs_uid'] .":$locale", 'cache_menu');
  }
}

/**
 * Implemenation of hook_project_page_link_alter().
 */
function drupalorg_project_page_link_alter($node, &$all_links) {
  // Link to security handbook page.
  $all_links['support']['links']['report_security_issue'] = l(t('Report a security issue'), 'security-team');
}
