<?php

/**
 * Prefix for variable names used to store advertisements.
 */
define('ADVERT_BLOCK_BODY', 'advert_block_body_');

/**
 * List of all ad blocks. This is the only place to add blocks to if you need more.
 */
function _advert_list_blocks() {
  $list = array();

  $list[0]['forum'] = 51;
  $list[0]['title'] = t('Paid services forum ad');

  $list[1]['forum'] = 34;
  $list[1]['title'] = t('Affiliate hosting header ad');

  $list[2]['forum'] = 51;
  $list[2]['title'] = t('Affiliate paid-services Ad with Google Ad Manager');

  return $list;
}

/**
 * Get master data for a particular block, by delta.
 */
function _advert_get_block($delta) {
  $list = _advert_list_blocks();
  return $list[$delta];
}

/**
 * Implementation of hook_block().
 */
function advert_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks = array();
      foreach(_advert_list_blocks() as $block_delta => $block_data) {
        $blocks[$block_delta]['info'] = $block_data['title'];
      }
      return $blocks;

    case 'configure':
      $form = array();

      // Provide form to enter ad details.
      $form[ADVERT_BLOCK_BODY . $delta] = array(
        '#type'          => 'textarea',
        '#title'         => t('HTML and/or Javascript'),
        '#description'   => t('Enter HTML and/or Javascript to display in this block'),
        '#default_value' => variable_get(ADVERT_BLOCK_BODY . $delta, ''),
      );
      return $form;

    case 'save':
      variable_set(ADVERT_BLOCK_BODY . $delta, $edit[ADVERT_BLOCK_BODY . $delta]);
      return;

    case 'view':
      $block_data = _advert_get_block($delta);
      $forum = $block_data['forum'];
      if (advert_is_in_forum($forum)) {
        $block['subject'] = $block_data['title'];
        $block['content'] = variable_get(ADVERT_BLOCK_BODY . $delta, '');
        return $block;
      }
  }
}

/** 
 * Are we in the appropriate forum to display that ad?
 */
function advert_is_in_forum($forum_id) {
  return ((arg(0) == 'forum') && (arg(1) == $forum_id)) ||
         ((arg(0) == 'node') && is_numeric(arg(1)) && ($node = menu_get_object()) && (($node->type == 'forum') && ($node->tid == $forum_id)));
}
