<?php
// $Id$

define('ADVERT_FORUM_PAID',    51);
define('ADVERT_FORUM_HOSTING', 34);
define('ADVERT_BLOCK_BODY',    'advert_block_body_');

function advert_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Paid services forum ad');
      $blocks[1]['info'] = t('Affiliate hosting header ad');
      $blocks[2]['info'] = t('Affiliate paid-services Ad with Google Ad Manager');
      return $blocks;

    case 'configure':
      $form = array();

      $form[ADVERT_BLOCK_BODY . $delta] = array(
        '#type'          => 'textarea',
        '#title'         => t('HTML and/or Javascript'),
        '#description'   => t('Enter HTML and/or Javascript to display in this block'),
        '#default_value' => variable_get(ADVERT_BLOCK_BODY . $delta, ''),
      );
      return $form;

    case 'save':
      variable_set(ADVERT_BLOCK_BODY . $delta, $edit[ADVERT_BLOCK_BODY . $delta]);
      return;

    case 'view':
      switch($delta) {
        case 0:
          if (advert_is_in_forum(ADVERT_FORUM_PAID)) {
            $block['subject'] = t('Paid services ad');
            $block['content'] = variable_get(ADVERT_BLOCK_BODY . $delta, '');
            return $block;
          }
          break;
        case 1:
          if (advert_is_in_forum(ADVERT_FORUM_HOSTING)) {
            $block['subject'] = t('Hosting forum ads');
            $block['content'] = variable_get(ADVERT_BLOCK_BODY . $delta, '');
            return $block;
          }
          break;
        case 2:
          if (advert_is_in_forum(ADVERT_FORUM_PAID)) {
            $block['subject'] = t('Affiliate Ads');
            $block['content'] = variable_get(ADVERT_BLOCK_BODY . $delta, '');
            return $block;
          }
          break;
      }
  }
}

function advert_is_in_forum($forum_id) {
  if (arg(0) == 'forum' && arg(1) == $forum_id) {
    return TRUE;
  }
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if ($node->type == 'forum' && $node->tid == $forum_id) {
      return TRUE;
    }
  }
  return FALSE;
}

