<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function bingo_menu() {
  $items['bug-bingo'] = array(
    'title'              => 'Bug bingo',
    'page callback'      => 'bingo_jump',
    'page arguments'     => array('bug-core'),
    'access arguments'   => array('access content'),
    'type'               => MENU_SUGGESTED_ITEM,
  );
  $items['contrib-bug-bingo'] = array(
    'title'              => 'Contrib bug bingo',
    'page callback'      => 'bingo_jump',
    'page arguments'     => array('bug-contrib'),
    'access arguments'   => array('access content'),
    'type'               => MENU_SUGGESTED_ITEM,
  );
  $items['patch-bingo'] = array(
    'title'              => 'Patch bingo',
    'page callback'      => 'bingo_jump',
    'page arguments'     => array('patch-core'),
    'access arguments'   => array('access content'),
    'type'               => MENU_SUGGESTED_ITEM,
  );
  $items['contrib-patch-bingo'] = array(
    'title'              => 'Contrib patch bingo',
    'page callback'      => 'bingo_jump',
    'page arguments'     => array('patch-contrib'),
    'access arguments'   => array('access content'),
    'type'               => MENU_SUGGESTED_ITEM,
  );
  return $items;
}

/**
 * SQL randomizer for issues.
 */
function bingo_jump($type = NULL) {
  $sql = array(
    // Bug, core.
    'bug-core' => "SELECT nid FROM {project_issues} WHERE sid IN (1) AND category = 'bug' AND pid = 3060 ORDER BY RAND() LIMIT 1",
    // Bug, contrib.
    'bug-contrib' => "SELECT nid FROM {project_issues} WHERE sid IN (1) AND category = 'bug' AND pid != 3060 ORDER BY RAND() LIMIT 1",
    // Patch, core.
    'patch-core' => "SELECT nid FROM {project_issues} WHERE sid IN (8,13,14) AND pid = 3060 ORDER BY RAND() LIMIT 1",
    // Patch, contrib.
    'patch-contrib' => "SELECT nid FROM {project_issues} WHERE sid IN (8,13,14) AND pid != 3060 ORDER BY RAND() LIMIT 1",
  );
  if (!isset($type) || !isset($sql[$type])) {
    $type = 'bug-core';
  }

  $nid = db_result(db_query($sql[$type]));
  if ($_GET['stop'] != 1) {
    drupal_goto('node/'. $nid);
  }
}

/**
 * Implementation of hook_block().
 */
function bingo_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Contributor links');
      return $blocks;

    case 'view':
      $block['subject'] = t('Contributor links');
      $block['content'] = bingo_block_output();
      return $block;
  }
}

/**
 * Output links with issue counts for different types of issues.
 */
function bingo_block_output() {
  $counts = variable_get('drupalorg_issue_counts', array());

  $counts_pending = $counts['Pending bugs'];
  $counts_critical = $counts['Critical issues'];
  $counts_queue = $counts['Patch queue'];
  $counts_review = $counts['Patches to review'];

  $versions = array_map('trim', explode(',', ISSUE_RIDS));
  $url_pending = drupalorg_drupal_issue_url(
    array(
      'version' => $versions,
      'status' => array(1),
      'priorities' => array(1, 2),
      'categories' => array('bug'),
    )
  );
  $url_critical = drupalorg_drupal_issue_url(
    array(
      'version' => $versions,
      'status' => array(1, 8, 13, 14),
      'priorities' => array(1),
      'categories' => array('bug', 'task'),
    )
  );
  $url_queue = drupalorg_drupal_issue_url(
    array(
      'version' => $versions,
      'status' => array(8, 13, 14),
    )
  );
  $url_review = drupalorg_drupal_issue_url(
    array(
      'version' => $versions,
      'status' => array(8, 14),
    )
  );
  $url_performance = drupalorg_drupal_issue_url(
    array(
      'version' => array('7.x'),
      'issue_tags' => 'Performance',
    )
  );
  $url_usability = drupalorg_drupal_issue_url(
    array(
      'version' => array('7.x'),
      'issue_tags' => 'Usability, d7ux',
    )
  );
  $url_fields = drupalorg_drupal_issue_url(
    array(
      'version' => array('7.x'),
      'issue_tags' => 'Fields in Core',
    )
  );

  $output = <<<EOT
<div class="item-list">
<ul>
  <li><a href="/community-initiatives">Community initiatives</a></li>
  <li>
    <strong>Queues</strong>
    <ul>
      <li>
        <a href="/project/issues/user">
          My issues
        </a>
      </li>
      <li>
        <a href="$url_pending">
          $counts_pending Pending bugs (D7)
        </a>
      </li>
      <li>
        <a href="$url_critical">
          $counts_critical Critical issues (D7)
        </a>
      </li>
      <li>
        <a href="$url_queue">
          $counts_queue Patch queue (D7)
        </a>
      </li>
      <li>
        <a href="$url_review">
          $counts_review Patches to review (D7)
        </a>
      </li>
      <li>
        <a href="$url_performance">
          Performance issues (D7)
        </a>
      </li>
      <li>
        <a href="$url_usability">
          Usability issues (D7)
        </a>
      </li>
      <li>
        <a href="$url_fields">
          Fields in Core issues (D7)
        </a>
      </li>
    </ul>
  </li>
  <li><strong>Play patch bingo!</strong>
  <ul>
   <li><a href="/patch-bingo" title="Select a random patch for review">Drupal core</a></li>
   <li><a href="/contrib-patch-bingo" title="Select a random patch for review from the contributions">Contributions</a></li>
 </ul>
 </li>
 <li><strong>Play bug bingo!</strong>
 <ul>
 <li><a href="/bug-bingo" title="Select a random bug to fix">Drupal core</a></li>
 <li><a href="/contrib-bug-bingo" title="Select a random bug to fix from the contributions">Contributions</a></li>
 </ul></li>
 <li><a href="/mailing-lists">Mailing list archives</a></li>
 <li><a href="/project/issues/webmasters">Drupal.org webmasters</a></li>
 <li><a href="/project/issues/infrastructure">Drupal.org server administrators</a></li>
 <li><strong>Web links</strong>
 <ul>
 <li><a href="/planet">Planet Drupal</a></li>
 <li><a href="/talk">Drupal talk</a></li>
 <li><a href="http://groups.drupal.org/drupal-dojo">Drupal dojo</a></li>
 </ul></li>
 </ul>
 </div>
EOT;
  return $output;
}
