<?php
// $Id$

define('BINGO_TYPE_MIN', 0);

// Make sure this corresponds to the number of menu items and queries
define('BINGO_TYPE_MAX', 3);

function bingo_menu($may_cache) {
  if ($may_cache) {
    $items[] = array(
      'path'               => 'patch-bingo',
      'callback'           => 'bingo_jump',
      'callback arguments' => array(0),
      'access' => user_access('access content'), 
      );
    $items[] = array(
      'path'               => 'contrib-patch-bingo',
      'callback'           => 'bingo_jump',
      'callback arguments' => array(1),
      'access' => user_access('access content'), 
      );
    $items[] = array(
      'path'               => 'bug-bingo',
      'callback'           => 'bingo_jump',
      'callback arguments' => array(2),
      'access' => user_access('access content'), 
      );
    $items[] = array(
      'path'               => 'contrib-bug-bingo',
      'callback'           => 'bingo_jump',
      'callback arguments' => array(3),
      'access' => user_access('access content'), 
      );
  }
  return $items;
}

function bingo_jump($type = BINGO_TYPE_MIN) {
  // Check that we got a valid argument
  if ($type < BINGO_TYPE_MIN || $type > BINGO_TYPE_MAX) {
    // otherwise fake a valid one!
    $type = BINGO_TYPE_MIN;
  }

  $sql = array(
    // Bug core
    "SELECT nid FROM {project_issues} WHERE sid IN (1) AND category = 'bug' AND pid = 3060 ORDER BY RAND() LIMIT 1",
    // Bug contrib
    "SELECT nid FROM {project_issues} WHERE sid IN (1) AND category = 'bug' AND pid != 3060 ORDER BY RAND() LIMIT 1",
    // Patch core
    "SELECT nid FROM {project_issues} WHERE sid IN (8,13,14) AND pid = 3060 ORDER BY RAND() LIMIT 1",
    // Patch contrib
    "SELECT nid FROM {project_issues} WHERE sid IN (8,13,14) AND pid != 3060 ORDER BY RAND() LIMIT 1",
  );

  $nid = db_result(db_query($sql[$type]));
  if ($_GET['stop'] != 1) {
    drupal_goto('node/'. $nid);
  }
}

function bingo_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('bingo: Contributor links');
      return $blocks;

    case 'view':
      $block['subject'] = t('Contributor links');
      $block['content'] = bingo_block_output();
      return $block;
  }
}

function bingo_spotlight_title() {
  $nid = 132970;
  $title = db_result(db_query("SELECT title FROM {node} WHERE nid = %d", $nid));
  $clean_title = str_replace('Patch spotlight: ', '', $title);
  return l($clean_title, 'node/' . $nid);
}

function bingo_block_output() {
  $spotlight = bingo_spotlight_title();

  $counts = variable_get('drupalorg_issue_counts', array());

  $counts_pending = $counts['Pending bugs'];
  $counts_critical = $counts['Critical issues'];
  $counts_queue = $counts['Patch queue'];
  $counts_review = $counts['Patches to review'];

  $output = <<<EOT
<div class="item-list">
<ul>
  <li><a href="http://drupal.org/search/node">Advanced search</a></li>
  <li>
    <strong>Queues</strong>
    <ul>
      <li>
        <a href="/project/issues/user">
          My issues
        </a>
      </li>
      <li>
        <a href="/project/issues?projects=3060&states=1&categories=bug&versions=156281&priorities=1,2">
          $counts_pending Pending bugs (D7)
        </a>
      </li>
      <li>
        <a href="/project/issues?projects=3060&categories=bug,task&priorities=1&states=1,8,13,14&versions=156281">
          $counts_critical Critical issues (D7)
        </a>
      </li>
      <li>
        <a href="/project/issues?projects=3060&states=8,13,14&versions=156281">
          $counts_queue Patch queue (D7)
        </a>
      </li>
      <li>
        <a href="/project/issues?projects=3060&states=8&versions=156281">
          $counts_review Patches to review (D7)
        </a>
      </li>
    </ul>
  </li>
  <li>
    <strong>Patch spotlight</strong>
     <ul>
       <li>$spotlight</li>
    </ul>
  </li>
  <li><strong>Play patch bingo!</strong>
  <ul>
   <li><a href="/patch-bingo" title="Select a random patch for review">Drupal core</a></li>
   <li><a href="/contrib-patch-bingo" title="Select a random patch for review from the contributions">Contributions</a></li>
 </ul>
 </li>
 <li><strong>Play bug bingo!</strong>
 <ul>
 <li><a href="/bug-bingo" title="Select a random bug to fix">Drupal core</a></li>
 <li><a href="/contrib-bug-bingo" title="Select a random bug to fix from the contributions">Contributions</a></li>
 </ul></li>
 <li><a href="/mailing-lists">Mailing list archives</a></li>
 <li><a href="/project/issues/webmasters">Drupal.org webmasters</a></li>
 <li><a href="/project/issues/infrastructure">Drupal.org server administrators</a></li>
 <li><strong>Web links</strong>
 <ul>
 <li><a href="/planet">Planet Drupal</a></li>
 <li><a href="/talk">Drupal talk</a></li>
 <li><a href="http://groups.drupal.org/drupal-dojo">Drupal dojo</a></li>
 </ul></li>
 </ul>
 </div>
EOT;
  return $output;
}

