<?php

/**
 * Implementation of hook_nodeapi().
 */
function branches_nodeapi(&$node, $op = 'view', $teaser = FALSE, $page = FALSE) {
  if ($op == 'view' && $page) {
    $extra = '';
    switch ($node->nid) {
      case 97084: // List branches ever created in contrib.
        $extra = branches_body_contrib();
        break;
      case 93997: // List branches ever created in core.
        $extra = branches_body_core();
        break;
    }
    $node->content['body']['#value'] .= $extra;
  }
}

/**
 * Show branches ever created in contrib based on CVS module data.
 */
function branches_body_contrib() {
  $output = '<ul>';
  $query= db_query("SELECT DISTINCT tag, COUNT(*) AS total
    FROM {cvs_tags}
    WHERE nid != 3060 AND nid != 0 AND tag RLIKE 'DRUPAL' AND branch = 1
    GROUP BY tag ORDER BY tag DESC");
  while($tag = db_fetch_object($query)) {
    $output .= ' <li>' . check_plain($tag->tag) . ' ('. format_plural($tag->total, '1 project', '@count projects') .')</li>';
  }
  $output .= '</ul>';
  return $output;
}

/**
 * Show branches ever created in core based on CVS module data.
 */
function branches_body_core() {
  $output = '<ul>';
  $query= db_query("SELECT tag
    FROM {cvs_tags}
    WHERE nid = 3060 AND branch = 1 AND tag != 'DRUPAL-3-00'
    ORDER BY tag DESC");
  while($tag = db_fetch_object($query)) {
    $output .= ' <li>' . check_plain($tag->tag) . '</li>';
  }
  $output .= '</ul>';
  $output .= '<a href="#tags"><h2 id="tags">Available tags</h2></a>';
  $output .= '<p>The tags currently available in Drupal core are:</p>';
  $output .= '<ul>';

  $query= db_query("SELECT tag
    FROM {cvs_tags}
    WHERE nid = 3060 AND branch = 0 AND tag RLIKE 'DRUPAL-'
    ORDER BY tag DESC");
  while($tag = db_fetch_object($query)) {
    $output .= ' <li>' . check_plain($tag->tag) . '</li>';
  }
  $output .= '</ul>';
  return $output;
}
