<?php
// $Id$

/**
 * @file
 * This file provides the pivots_blocks that generates module recommendations.
 *
 * Current limitations/issues:
 *   1. Recommendation data is stored externally on master-other.drupal.org database.
 *      The reason to use external database is to give flexibility to developers to tweak the algorithm.
 *   2. "More" is disabled temporarily to make the code clearer, will be added later if needed.
 */

define('PID_CONVERSATION', 4151); // conversation pivot algorithm ID that displays related conversations
define('PID_DOUBLE', 4158);       // double pivot algorithm ID that displays related projects in different algorithms.
define('LIMIT_CONVERSATION', 5);
define('LIMIT_DOUBLE', 5);
define('LIMIT_MAX', 100);         // maximum items to display in the block or on a page.

function pivots_block_output() {
  if ($node = project_get_project_from_menu()) {
    
    //HACK: randomize algorithm rotation 
    global $_pivots_block_pid_double;  // double pivot ID defaults to conversation pivots
    switch (rand(0,4)) {
      case 0:
        $_pivots_block_pid_double = 4158; // conversation pivots
        break;
      case 1:
        $_pivots_block_pid_double = 4157; // co-installation
        break;
      case 2:
        $_pivots_block_pid_double = 4159; // Solr-30
        break;
      case 3:
        $_pivots_block_pid_double = 4160; // Solr-100
        break;
      case 4:
        $_pivots_block_pid_double = 4161; // Solr-10
        break;
    }
    
    $output = _pivots_block_display_on_project($node->nid); 
    if (!empty($output)) {
      $GLOBALS['conf']['googleanalytics_codesnippet_after'] .= "pageTracker._trackEvent('PivotsPageview_{$_pivots_block_pid_double}', 'pivotsfrom_{$node->nid}');";
    }
    return $output;
  }
}

function _pivots_block_display_on_project($node_id) {
  global $_pivots_block_pid_double;
  $output = '';
  $output .= _pivots_block_content($node_id, PID_CONVERSATION, t("Related discussions"), LIMIT_CONVERSATION);
  $output .= _pivots_block_content($node_id, $_pivots_block_pid_double, t("Related projects"), LIMIT_DOUBLE); 
  return $output;
}

function _pivots_block_display_on_forum($node_id) {
  $output = '';
  $output = _pivots_block_content($node_id, PID_CONVERSATION, t("Projects mentioned in the discussion"), LIMIT_CONVERSATION); 
  return $output; 
}

function _pivots_block_content($node_id, $pivot_id, $title, $limit) {
  $output = '';
  $items = _pivots_block_generate_items($node_id, $pivot_id, $limit);  
  if (!empty($items)) {
    foreach ($items as $position => $item) {
      $items[$position] = l($item['title'], "node/{$item['nid']}", array( 'attributes' => array(
        "onClick" => "javascript:pageTracker._trackEvent('PivotsClick_${pivot_id}', 'pivotsfrom_${node_id}', 'pivotsto_${item['nid']}');"
      )));
    }
    $output = theme('item_list', $items, $title); 
  }
  return $output;
}

function _pivots_block_generate_items($node_id, $pivot_id, $limit) {
  if ($limit <= 0) {
    $limit = LIMIT_MAX;
  }  
  
  db_set_active('pivots');  // NOTE: here we activate the pivots database.  
  // if there's database failure, we just pretend nothing happens whatsoever. pivots_block returns nothing in this case.
  $matches = @db_query("SELECT DISTINCT dest_id FROM {pivots_match} WHERE pivot_id=%d AND src_id=%d 
        AND dest_id<>%d ORDER BY score DESC", $pivot_id, $node_id, $node_id);
  db_set_active();  // NOTE: change back to use the default database
  
  $count = 0;
  $items = array();
  while (($match = @db_fetch_array($matches)) && $count < $limit) {
    $dest_id = $match['dest_id'];
    $result = db_query("SELECT title FROM {node} WHERE nid=%d AND status=1", $dest_id);
    // there might be cases that the node was deleted, or set to unpublished between pivots database refresh
    // so here we only count the valid node.
    $title = db_result($result);
    if ($title) {
      $items[] = array('nid' => $dest_id, 'title' => $title, 'pid' => $pivot_id);
      $count++;
    }
  }  
  return $items;
}

/**
 * Implementation of hook_block()
 */
function pivots_block_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('pivots_block: Recommendations');
      return $blocks;

    case 'view':
      $block['subject'] = t('Recommendations');
      $block['content'] = pivots_block_output();
      return $block;
  }
}
