<?php
// $Id$

/**
 * @file
 * This file provides the pivots_blocks that generates module recommendations.
 *
 * Current limitations/issues:
 *   1. Recommendation data is stored externally on master-other.drupal.org database.
 *      The reason to use external database is to give flexibility to developers to tweak the algorithm.
 *   2. "More" is disabled temporarily to make the code clearer, will be added later if needed.
 */

define('LIMIT_CONVERSATION', 5);
define('LIMIT_DOUBLE', 5);
define('LIMIT_MAX', 100);         // maximum items to display in the block or on a page.

function pivots_block_output() {
  if (arg(0) != 'node' || !is_numeric(arg(1))) {
    return;
  }
  $node_id = arg(1);
  $node = node_load($node_id);
  $output = '';
  
  // Hack: alternate pivots algorithms.
  // Explanation at: http://mrzhou.cms.si.umich.edu/pivots-algorithms-explanation
  global $_pivots_block_pid_conversation, $_pivots_block_pid_double;
  $_pivots_block_pid_conversation = 4151; // conversation pivot ID that displays related conversations
  $_pivots_block_pid_double = 4153;  // double pivot ID that displays related projects
  $time_1 = 1224907200; // 2008-10-25 00:00:00
  $time_2 = 1225166400; // 2008-10-28 00:00:00
  $time_3 = 1225425600; // 2008-10-31 00:00:00
  $time_4 = 1225688400; // 2008-11-03 00:00:00
  $curr_time = time() - 28800; // Current time on D.O. (UTC) to PST(-8:00) used in Google Analytics
  if ($curr_time>=$time_1 && $curr_time<$time_2) {
    $_pivots_block_pid_double = 4152;  // co-references algorithm
  }
  else if ($curr_time>=$time_2 && $curr_time<$time_3) {
    $_pivots_block_pid_double = 4154;  // recency algorithms
  }
  else if ($curr_time>=$time_3 && $curr_time<$time_4) {
    $_pivots_block_pid_double = 4155;  // uniqueness algorithms
  }
  // else remain 4153, the default "relevancy" algorithm.
  
  if ($node->type == 'project_project') {
    $output = _pivots_block_display_on_project($node_id); 
  }
  else if ($node->type == 'forum') {
    $output = _pivots_block_display_on_forum($node_id);
  }
  else {
    // $output = null; 
  }
    
  return $output;
}

function _pivots_block_display_on_project($node_id) {
  global $_pivots_block_pid_conversation, $_pivots_block_pid_double;
  $output = '';
  $output .= _pivots_block_content($node_id, $_pivots_block_pid_conversation, t("Related discussions"), LIMIT_CONVERSATION);
  $output .= _pivots_block_content($node_id, $_pivots_block_pid_double, t("Related projects"), LIMIT_DOUBLE); 
  return $output;
}

function _pivots_block_display_on_forum($node_id) {
  global $_pivots_block_pid_conversation;
  $output = '';
  $output = _pivots_block_content($node_id, $_pivots_block_pid_conversation, t("Projects mentioned in the discussion"), LIMIT_CONVERSATION); 
  return $output; 
}

function _pivots_block_content($node_id, $pivot_id, $title, $limit) {
  $output = '';
  $items = _pivots_block_generate_items($node_id, $pivot_id, $limit);  
  if (!empty($items)) {
    foreach ($items as $position => $item) {
      $items[$position] = l($item['title'], "node/{$item['nid']}", array(
        "onClick" => "javascript:urchinTracker('/pivotslog/$pivot_id/$node_id/{$item['nid']}/$position');"
      ));
    }
    $output = theme('item_list', $items, $title); 
  }
  return $output;
}

function _pivots_block_generate_items($node_id, $pivot_id, $limit) {
  if ($limit <= 0) {
    $limit = LIMIT_MAX;
  }  
  
  db_set_active('pivots');  // NOTE: here we activate the pivots database.  
  // if there's database failure, we just pretend nothing happens whatsoever. pivots_block returns nothing in this case.
  $matches = @db_query("SELECT DISTINCT dest_id FROM {pivots_match} WHERE pivot_id=%d AND src_id=%d 
        AND dest_id<>%d ORDER BY score DESC", $pivot_id, $node_id, $node_id);
  db_set_active();  // NOTE: change back to use the default database
  
  $count = 0;
  $items = array();
  while (($match = @db_fetch_array($matches)) && $count < $limit) {
    $dest_id = $match['dest_id'];
    $result = db_query("SELECT title FROM {node} WHERE nid=%d AND status=1", $dest_id);
    // there might be cases that the node was deleted, or set to unpublished between pivots database refresh
    // so here we only count the valid node.
    if (db_num_rows($result) > 0) {
      $title = db_result($result);
      $items[] = array('nid' => $dest_id, 'title' => $title, 'pid' => $pivot_id);
      $count++;
    }
  }  
  return $items;
}

/**
 * Implementation of hook_block()
 */
function pivots_block_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('pivots_block: Recommendations');
      return $blocks;

    case 'view':
      $block['subject'] = t('Recommendations');
      $block['content'] = pivots_block_output();
      return $block;
  }
}

