<?php
// $Id$

/**
 * Implementation of hook_nodeapi().
 */
function quick_stats_nodeapi(&$node, $op = 'view', $teaser = FALSE, $page = FALSE) {
  if ($op == 'view' && $page) {
    $extra = '';
    switch ($node->nid) {
      case 190833:
        $extra = quick_stats_report();
        break;
    }
    $node->content['body']['#value'] .= $extra;
  }
}

/**
 * Overall quick stats for drupal.org.
 */
function quick_stats_report() {
  $output .=  "<dl>";

  $nodes = db_result(db_query("SELECT COUNT(*) FROM {node} WHERE status = 1"));
  $output .=  "<dt>All content nodes:</dt><dd>". $nodes ." (excluding unpublished nodes)</dd>";

  $nodes_last_year = db_result(db_query("SELECT COUNT(*) FROM {node} WHERE created > %d AND status = 1", strtotime("1 year ago", time())));
  $output .=  "<dt>All content nodes in the last year:</dt><dd>". $nodes_last_year ." (excluding unpublished nodes)</dd>";

  $book = db_result(db_query("SELECT COUNT(*) FROM {node} WHERE type = 'book' AND status = 1"));
  $output .=  "<dt>Book nodes:</dt><dd>". $book ."</dd>";

  $users = db_result(db_query("SELECT COUNT(*) FROM {users} WHERE status = 1"));
  $output .=  "<dt>Users:</dt><dd>". $users ." (excludes blocked users)</dd>";

  $comments = db_result(db_query("SELECT COUNT(*) FROM {comments} WHERE status = 1"));
  $output .=  "<dt>Comments:</dt><dd>". $comments ." (excluding unpublished comments)</dd>";
  
  $projects = db_result(db_query("SELECT COUNT(*) FROM {project_projects}"));
  $output .=  "<dt>Total projects:</dt><dd>". $projects ."</dd>";

  $issues = db_result(db_query("SELECT COUNT(*) FROM {node} WHERE type = 'project_issue' AND status = 1"));
  $output .=  "<dt>Total issues:</dt><dd>". $issues ." (excluding unpublished issues)</dd>";

  $issues_year = db_result(db_query("SELECT COUNT(*) FROM {node} WHERE type = 'project_issue' AND created > %d AND status = 1", strtotime("1 year ago", time())));
  $output .=  "<dt>Issues in the last Year:</dt><dd>". $issues_year ."</dd>";

  $followups = db_result(db_query("SELECT COUNT(*) FROM {node} n INNER JOIN {comments} c ON n.nid = c.nid WHERE n.type = 'project_issue' AND n.status = 1"));
  $output .=  "<dt>Followups on issues:</dt><dd>". $followups ."</dd>";

  $followups_year = db_result(db_query("SELECT COUNT(*) FROM {node} n INNER JOIN {comments} c ON n.nid = c.nid WHERE n.type = 'project_issue' AND n.status = 1 AND n.created > (UNIX_TIMESTAMP() - 24 * 60* 60* 365)"));
  $output .=  "<dt>Followups on issues in last year:</dt><dd>". $followups_year ."</dd>";

  $cvs_accts_approved = db_result(db_query('SELECT COUNT(*) FROM {cvs_accounts} WHERE status = %d', CVS_APPROVED));
  $output .=  "<dt>CVS accounts:</dt><dd>". $cvs_accts_approved ."</dd>";

  $cvs_commits = db_result(db_query('SELECT COUNT(*) FROM {cvs_messages}'));
  $output .=  "<dt>CVS commits:</dt><dd>". $cvs_commits ."</dd>";

  $cvs_commits_year = db_result(db_query('SELECT COUNT(*) FROM {cvs_messages} WHERE created > %d', strtotime("1 year ago")));
  $output .=  "<dt>CVS commits in last year:</dt><dd>". $cvs_commits_year ."</dd>";

  $output .=  "</dl>";

  return $output;
}
