<?php
// $Id$

function redirects_nodeapi(&$node, $op = 'view', $teaser = FALSE, $page = FALSE) {
  if ($op == 'view' && $page) {
    switch ($node->nid) {
      case 9730:
        header('Location: http://drupal.org/project/issues?projects=3060&states=8,13,14');
        exit;

      case 9731:
        header('Location: http://drupal.org/project/issues?projects=3060&states=1&categories=bug');
        exit;

      case 9732:
        header('Location: http://www.drupal.org/project/issues?projects=3060&states=1&categories=task');
        exit;

      case 133282:
        drupal_goto('patch/create');
    }
  }
}

function redirects_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'project/Drupal project',
      'access' => user_access('access content'),
      'callback' => 'drupal_goto',
      'callback arguments' => array('project/drupal'),
    );
    $items[] = array(
      'path' => 'project/drupal project',
      'access' => user_access('access content'),
      'callback' => 'drupal_goto',
      'callback arguments' => array('project/drupal'),
    );
    $items[] = array(
      'path' => 'download',
      'access' => user_access('access content'),
      'callback' => 'drupal_goto',
      'callback arguments' => array('project/drupal'),
    );
  }
  return $items;
}

