<?php
// $Id$

function searchquery_nodeapi(&$node, $op = 'view', $teaser = FALSE, $page = FALSE) {
  if ($op == 'view' && $page) {
    $extra = '';
    switch ($node->nid) {
      case 48380:
        $extra = searchquery_list();
        break;
    }
    $node->content['body']['#value'] .= $extra;
  }
}

function searchquery_list() {
  if ($cache = cache_get('node_48380')) {
    return $cache->data;
  }

  $output .= '<div class="column-left"><h2>Anonymous users</h2><ul>';
  $result = db_query("SELECT message, COUNT(message) AS cnt FROM {watchdog}
    WHERE type = 'search' AND uid = 0
    GROUP BY message
    ORDER BY cnt DESC
    LIMIT 300");

  while ($s = db_fetch_object($result)) {
    preg_match('!<em>(.*?)</em>!', $s->message, $matches);
    $output .= '<li>'. check_plain($matches[1]) .' ('. $s->cnt .')</li>';
  }
  $output .= '</ul></div>';

  $output .= '<div class="column-right"><h2>Authenticated users</h2><ul>';
  $result = db_query("SELECT message, COUNT(message) AS cnt FROM {watchdog}
    WHERE type = 'search' AND uid != 0
    GROUP BY message
    ORDER BY cnt
    DESC limit 300");

  while ($s = db_fetch_object($result)) {
    preg_match('!<em>(.*?)</em>!', $s->message, $matches);
    $output .= '<li>'. check_plain($matches[1]) .' ('. $s->cnt .')</li>';
  }
  $output .= '</ul></div>';

  cache_set('node_48380', $output, 'cache', 60*60);

  return $output;
}
