<?php

/**
 * Add code filter and linebreaks security filter to ckeditor.
 */
function drupalorg_wysiwyg_ckeditor_security_filter() {

  return array(
    'codefilter' => array(
      'title' => 'Code Filter',
      'project_page' => 'http://drupal.org/project/codefilter',
      'description' => 'Converts code and pre tags into formats that are readible by ckeditor',
      'weight' => 0,
      'installed' => FALSE,
      'filters' => array()
    ),
    'filter_autop' => array(
      'title' => 'Core Linebreaks',
      'project_page' => 'http://drupal.org/project/drupal',
      'description' => 'Convert line breaks into HTML (i.e. br and p)',
      'weight' => 1,
      'installed' => FALSE,
      'filters' => array()
    ),
    'filter_html_image_secure' => array(
      'title' => 'Local Images',
      'project_page' => 'http://drupal.org/project/filter_html_image_secure',
      'description' => 'Filters out external image urls',
      'weight' => 1,
      'installed' => FALSE,
      'filters' => array()
    ),
  );
}
