<?php

/**
 * Implementation of hook_content_default_fields().
 */
function drupalorg_packaging_whitelist_content_default_fields() {
  $fields = array();

  // Exported field: field_packaging_whitelist_urls
  $fields['packaging_whitelist-field_packaging_whitelist_urls'] = array(
    'field_name' => 'field_packaging_whitelist_urls',
    'type_name' => 'packaging_whitelist',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => '20',
      'size' => 60,
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_packaging_whitelist_urls][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Allowed URLs',
      'weight' => '-4',
      'description' => '',
      'type' => 'text_textarea',
      'module' => 'text',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Allowed URLs');

  return $fields;
}
