<?php
// $Id$

/**
 * @file
 *   Module to provides XML-RPC server code for legacy update_status 5.x-1.* clients
 */

/**
 * Implementation of hook_xmlrpc().
 */
function project_xmlrpc_legacy_xmlrpc() {
  $xmlrpc = array();
  $xmlrpc[] = array(
    'project.release.data',
    'project_xmlrpc_legacy_data',
    t('Provides versioning data for a project or array of projects'),
  );
  return $xmlrpc;
}

/**
 * Callback for hook_xmlrpc().
 *
 * Returns hard-coded data for the update_status 5.x-2.3 official release.
 */
function project_xmlrpc_legacy_data($project = NULL, $api_version = NULL, $major_version = NULL) {
  $data = array();

  $data['update_status'] = array(
    'name' => 'Update status',
    'version' => '5.x-2.3',
    'version_major' => 2,
    'version_minor' => '',
    'version_patch' => 3,
    'version_extra' => '',
    'link' => url('http://drupal.org/project/update_status', array('absolute' => TRUE)),
    'release' => url('http://drupal.org/node/295470', array('absolute' => TRUE)),
    'download' => theme('project_release_download_link', 'files/projects/update_status-5.x-2.3.tar.gz', NULL, 'url'),
    'date' => 1218740721,
    'md5hash' => '0f9602dad6879af88dc9d86f06ab5149',
  );

  // Compress the data to reduce bandwidth usage. Base64 because binary data
  // does not seem to survive the XMLRPC transfer.
  $data = base64_encode(gzencode(serialize($data), 9, FORCE_GZIP));
  return $data;
}
