<?php

/**
 * Implementation of hook_honeypot_timelimit
 */
function drupalorg_honeypot_honeypot_time_limit($timelimit, $form_values, $failures) {
  global $user;

  $extra_time = 0;
  $count = 0;
  // scan nodes
  if (isset($form_values['title']) && $form_values['title']) {
    $count += drupalorg_honeypot_scan($form_values['title']);
  }
  if (isset($form_values['body']) && $form_values['body']['und'][0]['value']) {
    $count += drupalorg_honeypot_scan($form_values['body']['und'][0]['value']);
  }

  // scan comments
  if (isset($form_values['subject']) && $form_values['subject']) {
    $count += drupalorg_honeypot_scan($form_values['subject']);
  }
  if (isset($form_values['comment_body']) && $form_values['comment_body']['und'][0]['value']) {
    $count += drupalorg_honeypot_scan($form_values['comment_body']['und'][0]['value']);
  }

  if ($count) {
    $extra_time += $count * $timelimit * variable_get('drupalorg_honeypot_factor', 1);
    watchdog('honeypot', 'Spammer %uname (%uid) earned %count spam points and %time extra time.', array('%uname' => $user->name, '%uid' => $user->uid, '%count' => $count, '%time' => $extra_time));
  }

  if ($extra_time) {
    static $message = TRUE;
    if ($message) {
      drupal_set_message(t('<p>As a part of our continued efforts to make Drupal.org a productive place to visit and work, we’ve made it harder for spammers to post on the site. To avoid seeing this message again, and to be able to post faster, you can request the “trusted” user role. Please note that users who frequently post valuable content will automatically gain the role after some time.</p>
<p><a href="!help_url">Learn about the “trusted” user role</a> and <a href ="!issue_url">make your request</a>.</p>', array('!issue_url' => '/node/add/project-issue/webmasters?component=User%20account&categories=support&title=Request%20for%20%27trusted%27%20role', '!help_url' => '/node/1887616')));
      $message = FALSE;
    }
  }

  return $extra_time;
}

/**
 * Super-simple text scanner
 *
 * @param $text (string) Text to scan
 */
function drupalorg_honeypot_scan($text) {
  $needles = variable_get('drupalorg_honeypot_strings', array());
  $text = strtolower($text);
  $count = 0;
  foreach ($needles as $needle) {
    $count += substr_count($text, $needle);
  }
  return $count;
}

