<?php
// $Id$

/**
 * @file
 *   Custom code for the news page, planet Drupal and similar pages.
 */

/**
 * Vocabulary used for news forum topic tagging.
 */
define('DRUPALORG_NEWS_VID', 34);

/**
 * Planet Drupal category in the aggregator.
 */
define('DRUPALORG_PLANET_CATEGORY', 2);

// == Core hooks ===============================================================

/**
 * Implementation of hook_menu().
 */
function drupalorg_news_menu() {
  $items['news'] = array(
    'title' => 'News',
    'page callback' => 'drupalorg_news_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['news/%drupalorg_news_term'] = array(
    'title' => 'News',
    'page callback' => 'drupalorg_news_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu loader. Load news term if it is indeed from the given vocabulary.
 */
function drupalorg_news_term_load($tid) {
  if (($term == taxonomy_get_term($tid)) && ($term->vid == DRUPALORG_NEWS_VID)) {
    return $term;
  }
  return NULL;
}

/**
 * One of the most visited pages of the site, so hardcode queries.
 */
function drupalorg_news_page($term) {
  if (!isset($tid)) {
    $result = pager_query(db_rewrite_sql('SELECT n.nid, n.sticky, n.created FROM {node} n WHERE n.promote = 1 AND n.status = 1 ORDER BY n.sticky DESC, n.created DESC'), variable_get('default_nodes_main', 10));
    // Add existing "front page" feed if main news page.
    $feed_url = url('rss.xml', array('absolute' => TRUE));
    drupal_add_feed($feed_url, variable_get('site_name', 'Drupal') .' '. t('RSS'));
  }
  else {
    $result = pager_query(db_rewrite_sql('SELECT n.nid, n.sticky, n.created FROM {node} n LEFT JOIN {term_node} t ON t.vid = n.vid WHERE n.promote = 1 AND n.status = 1 AND t.tid = %d ORDER BY n.sticky DESC, n.created DESC'), variable_get('default_nodes_main', 10), 0, NULL, $term->tid);
  }

  $output = '';
  while ($node = db_fetch_object($result)) {
    $output .= node_view(node_load($node->nid), 1);
  }
  $output .= theme('pager', NULL, variable_get('default_nodes_main', 10));
  return $output;
}

// == Altering existing behavior ===============================================

/**
 * Implementation of hook_form_alter().
 */
function drupalorg_news_form_alter(&$form, $form_state, $form_id) {
  // Remove the news vocabulary on forum forms, if the user is not an admin.
  // Used to mark news forum topics with tags.
  if ($form_id == 'forum_node_form') {
    $form['taxonomy'][DRUPALORG_NEWS_VID]['#access'] = user_access('administer nodes'); 
  }
}

/**
 * Implementation of template_preprocess_drupalorg_home().
 *
 * @todo
 *   Add caching.
 */
function drupalorg_news_preprocess_drupalorg_home(&$vars) {
  // Get the first three news items ordered by descending publication date.
  $result = db_query_range('SELECT nid FROM {node} WHERE promote = 1 ORDER BY created DESC', array(), 0, 4);
  $fresh_news = '';
  $news_count = 0;
  while ($nid = db_fetch_object($result)) {
    $node = node_load($nid->nid);
    if ($news_count == 0) {
      // The first news item has a blurb displayed.
      $fresh_news .= '<h6>'. l($node->title, 'node/'. $node->nid) .'</h6>';
      $fresh_news .= '<p class="submitted">'. format_date($node->created, 'custom', 'F j, Y') .'</p>';
      // Cut it to short and sweet to fit into the design. Strip all tags,
      // so things like big images, distracting links and paragraph tags will
      // not end up here. The text should be good in itself to display.
      $fresh_news .= '<p>'. node_teaser(strip_tags($node->teaser), $node->format, 180) .' '. l(t('Read more'), 'node/'. $node->nid) .'</p>';
    }
    else {
      // Rest of the items have just their title displayed.
      $fresh_news .= '<p>'. l($node->title, 'node/'. $node->nid) .'</p>';
    }
    $news_count++;
  }
  // Finally, we have a link to the rest of the items
  $fresh_news .= '<p>'. l(t('More news…'), 'news') .'</p>';
  $vars['tab_content_news'] = $fresh_news;
}

// == Blocks for news and planet ===============================================

/**
 * Implementation of hook_block().
 */
function drupalorg_news_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['planet-list']['info'] = t('Planet Drupal subscriptions');
      $blocks['news-terms']['info']  = t('News category filter links');
      $blocks['news-sources']['info']  = t('News sources');
      return $blocks;

    case 'view':
      switch ($delta) {
        case 'planet-list':
          $block['subject'] = t('Planet Drupal subscriptions');
          $block['content'] = drupalorg_news_planet_drupal_block();
          return $block;
        case 'news-terms':
          $block['subject'] = t('Filter News');
          $block['content'] = drupalorg_news_filter_news();
          return $block;
        case 'news-sources':
          $block['content'] = t('<p>This page gathers:</p>');
          $block['content'] .= t('<a href="http://association.drupal.org/">Association</a> members’ blog posts<br />');
          $block['content'] .= t('<a href="/news">Official Drupal news</a> and announcements<br />');
          $block['content'] .= t('<a href="/planet">Planet Drupal</a> entries (Planet Drupal aggregates Drupal-related blog posts of special interest to the community)');
          return $block;
      }
  }
}

/**
 * Block to show the list of sources for the Planet as well as their count.
 */
function drupalorg_news_planet_drupal_block() {
  $output = '';
  $description = db_result(db_query("SELECT description FROM aggregator_category WHERE cid = %d", DRUPALORG_PLANET_CATEGORY));
  $result = db_query('SELECT f.* FROM {aggregator_feed} f JOIN {aggregator_category_feed} c ON f.fid = c.fid WHERE c.cid = %d ORDER BY f.title', DRUPALORG_PLANET_CATEGORY);

  $list = '<div class="item-list"><ul>';
  $counter = 0;
  while ($feed = db_fetch_object($result)) {
    $list .= '<li>'.  l($feed->title, $feed->link)  .' ('. l('feed', $feed->url) .')</li>'; 
    $counter++;
  }
  $list .= '</ul></div>';
  
  $output .= '<p>'. filter_xss_admin($description) .' '. t('Collecting posts from the following @num sources:', array('@num' => $counter)) .'</p>';
  $output .= $list;
  $output .= theme('xml_icon', url('planet/rss.xml'));

  return $output;
}

/**
 * News filtering by taxonomy term for the frontpage.
 */
function drupalorg_news_filter_news() {
  $tree = taxonomy_get_tree(DRUPALORG_NEWS_VID);
  $list_of_terms = array(array('title' => t('All news'), 'href' => 'news'));
  foreach ($tree as $term) {
    $list_of_terms[] = array('title' => $term->name, 'href' => 'news/'. $term->tid);
  }
  // Using theme links should mark active links with a class, so styling
  // can be applied to them properly.
  return theme('links', $list_of_terms);
}
