#! /usr/bin/php
<?php

// Load shared functionality.
require_once './shared.php';

if (!$repo_data = json_decode($repo_json)) {
  echo "Repository metadata was not found. Push cannot be safely accepted; rejecting all ref updates.\n";
  exit(1);
}

$stdin = fopen('php://stdin', 'r');
$payload = array(
  'uid' => $pusher_uid,
  'repo_id' => $repo_id,
  'git hook' => 'post-receive',
  'data' => stream_get_contents($stdin),
  'timestamp' => time(),
);
fclose($stdin);

_githooks_enqueue_job('versioncontrol_git_repo_parsing', $payload);