<?php

/**
 * @file
 *   Customizations and blocks for the handbook pages.
 */

/**
 * Implements hook_node_view().
 */
function drupalorg_handbook_node_view($node, $view_mode = 'full') {
  if ($view_mode == 'full') {
    $extra = '';
    switch ($node->nid) {
      case 322: // Mailing list subscription
        $extra = drupal_get_form('lists_subscribe_form');
        break;
      case 13355: // Site maintainers
        $extra = drupalorg_handbook_site_maintainers();
        break;
      case 263594: // Revision maintainers
        $extra = drupalorg_handbook_revision_maintainers();
        break;
    }

    if (!is_string($extra)) {
      $extra = drupal_render($extra);
    }
    $node->content['extra'] = array(
      '#markup' => $extra,
      '#weight' => 1,
    );

    $section = drupalorg_crosssite_section();

    if (isset($node->book['bid']) && ($section === 'documentation' || $section === 'community')) {

      // Prepend information about the page.
      $node->content['body']['#prefix'] = drupalorg_handbook_before_body($node);

      // Mark the taxonomy items as rendered so they don't display on the node.
      // These are elements of $node->content that are named
      // 'taxonomy_vocabulary_*'.
      foreach ($node->content as $key => $value) {
        if (strpos($key, 'taxonomy_vocabulary_') === 0) {
          hide($node->content[$key]);
        }
      }

      // Add the extra footer line.
      if ($section === 'documentation') {
        $node->content['extra_footer'] = array(
          '#markup' => theme('drupalorg_handbook_footer_line'),
          '#weight' => 150,
        );
      }

      // Add a "report to moderator" link.
      $node->content['links']['drupalorg_report'] = array(
        '#theme' => 'links__node__drupalorg',
        '#links' => array(
          'report' => drupalorg_handbook_moderate_link_info($node),
        ),
        '#attributes' => array('class' => array('links', 'inline')),
      );
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function drupalorg_handbook_node_insert($node) {
  if (!empty($node->book) && !empty($node->book['bid'])) {
    // Remove all cached versions of recently updated data (home).
    cache_clear_all('drupalorg_handbook_recent_updates_', 'cache', TRUE);
  }
}

/**
 * Returns the link information for the Report to moderator link.
 *
 * @param $node
 *   The node to make the link for.
 *
 * @return
 *   An array for the link (suitable for theme('link')), or NULL if the user
 *   does not have permission to create issues.
 */
function drupalorg_handbook_moderate_link_info($node) {
  if (!user_access('create project issues') || drupalorg_crosssite_section() !== 'documentation') {
    return NULL;
  }
  return array(
    'title' => t('Report to moderator'),
    'href' => 'node/add/project-issue/documentation',
    'query' => array(
      'categories' => 'task',
      'component' => 'Vandalism/Spam',
      'title' => t('Moderation report for !title', array('!title' => $node->title)),
      'body' => t('I am reporting !url to moderators because:', array('!url' => url('node/' . $node->nid, array('absolute' => TRUE)))),
    ),
  );
}

/**
 * Creates a list of who recently updated a page, and call to edit.
 *
 * @param $node
 *   The node object.
 *
 * @return
 *   HTML for the list of contributors with call to edit.
 *
 * @see handbook-contributors.tpl.php
 */
function drupalorg_handbook_before_body($node) {
  $format = 'F j, Y';
  $modified = t('Last updated @changed.', array('@changed' => format_date($node->changed, 'custom', $format)));
  $created = '';
  $contributors = '';
  $edit_link = '';
  if (drupalorg_crosssite_section() === 'documentation') {
    $created = t('Created by !author on @created.', array('!author' => theme('username', array('account' => $node)), '@created' => format_date($node->created, 'custom', $format)));
    // Make a list of the 4 most recent different revision authors, not including
    // the original author.
    $contributor_list = array();
    foreach (node_revision_list($node) as $revision) {
      if (!isset($contributor_list[$revision->uid]) && $revision->uid !== $node->uid) {
        $contributor_list[$revision->uid] = theme('username', array('account' => $revision));
      }
      if (count($contributor_list) >= 4) {
        break;
      }
    }
    if (!empty($contributor_list)) {
      $contributors = t('Edited by !contributors.', array('!contributors' => implode(', ', $contributor_list)));
    }

    if (node_access('update', $node)) {
      $edit_link = t('You can <a href="!url">edit this page</a>', array('!url' => url('node/' . $node->nid . '/edit'))) . (empty($contributor_list) ? '.' : t(', too.'));
    }
    elseif (!user_is_logged_in()) {
      $edit_link = l(t('Log in to edit this page'), 'user', array('query' => drupal_get_destination())) . '.';
    }
  }
  return theme('drupalorg_handbook_contributors', array('created' => $created, 'updated' => $modified, 'contributors' => $contributors, 'edit_link' => $edit_link));
}

/**
 * Gathers meta-data information for the book page sidebar.
 *
 * @return
 *   HTML for the book page sidebar.
 */
function drupalorg_handbook_meta_data() {
  static $about;

  if (!isset($about)) {
    $about = array('status' => '');
    $node = menu_get_object();
    $vocabularies = taxonomy_get_vocabularies();

    if (!$node) {
      return $about;
    }

    foreach (field_info_instances('node', $node->type) as $instance) {
      $field = field_info_field($instance['field_name']);
      if ($field['module'] === 'taxonomy' && count($node->{$field['field_name']}) > 0) {
        foreach (field_available_languages('node', $field) as $langcode) {
          foreach ($node->{$field['field_name']}[$langcode] as $item) {
            $term_id = $item['tid'];
            $term = $item['taxonomy_term'];

            if (isset($vocabularies[$term->vid])) {
              switch ($term->vid) {
              case 31:
                // Page status vocabulary: build status line.
                $class = 'page-ok';
                switch ($term_id) {
                case 126: // Incomplete.
                case 128: // Needs updating.
                case 18960: // Needs tech review.
                case 18962: // Needs copy/style review.
                case 18964: // Needs dividing.
                  $class = 'page-needs-work';
                  break;

                case 127: // Insecure.
                case 129: // Deprecated.
                  $class = 'page-major-problem';
                  break;
                }
                $about['status'] = '<p class="page-status ' . $class . '"><span>' . check_plain($term->name) . '</span></p>';
                break;

              case 54:
                // Keywords vocabulary: print a link, separate section.
                $keywords[] = l($term->name, 'taxonomy/term/' . $term->tid);
                break;

              default:
                // Any other vocabulary: print the name.
                $vocab_name = check_plain($vocabularies[$term->vid]->name);
                $about[$vocab_name][] = check_plain($term->name);
                break;
              }
            }
          }
        }
      }
    }

    if (!empty($keywords)) {
      // Keywords at the end.
      $about[t('Keywords')] = $keywords;
    }
  }

  return $about;
}

/**
 * List usernames with site maintainer role.
 */
function drupalorg_handbook_site_maintainers() {
  $output = 'If you have been around for a while, and you want to help maintain Drupal.org and are willing to accept the added responsibilities that come with it, sign up on the <a href="http://drupal.org/mailing-lists">Infrastructure team</a> list.';
  $output .= '<ol>';
  $result = db_query("SELECT DISTINCT(u.uid), u.name
    FROM {users} u INNER JOIN {users_roles} r ON u.uid = r.uid
    WHERE r.rid = :role1 OR r.rid = :role2 OR r.rid = :role3
    ORDER BY u.name ", array(':role1' => 3, ':role2' => 4, ':role3' => 9)); // 3 = site maintainer, 4 = administrator
  foreach ($result as $account) {
    $output .= "<li>" . theme('username', array('account' => $account)) . "</li>";
  }
  $output .= '</ol>';
  return $output;
}

/**
 * Collect and cache revision maintainers (those who made revisions to books).
 *
 * If the page visited is node/263594/filter, then filter is used as an input
 * to strtotime(), to limit to revisions after that date/time.
 */
function drupalorg_handbook_revision_maintainers() {
  $filter = check_plain(arg(2));
  $cache_key = 'node_263594-' . $filter;
  if ($cache = cache_get($cache_key)) {
    return $cache->data;
  }

  $since = 0;
  $output = '';
  if ($filter) {
    $trial = strtotime($filter);
    if ($trial) {
      $since = $trial;
      $output .= '<p>' . t('Contributions since !filter', array('!filter' => $filter)) . '</p>';
    }
  }

  $result = db_query("SELECT u.uid, u.name, COUNT(nr.vid) AS pages
    FROM {node} n INNER JOIN {node_revision} nr ON n.nid = nr.nid INNER JOIN {users} u ON u.uid = nr.uid
    WHERE n.type = :ntype AND n.status = :nstatus AND nr.timestamp > :nrtimestamp
    GROUP BY u.name
    ORDER BY pages DESC", array(':ntype' => 'book', ':nstatus' => 1, ':nrtimestamp' => $since));

  $list = array();
  $total = 0;
  $count = 0;
  foreach ($result as $contributor) {
    $list[] = theme('username', array('account' => $contributor)) . " (" . format_plural($contributor->pages, "@count revision", "@count revisions") . ")";
    $total += $contributor->pages;
    $count++;
  }

  $output .= '<p>' . format_plural($count, '@count contributor', '@count contributors') . '</p>';
  $output .= '<p>' . format_plural($total, '@count total revision', '@count total revisions') . '</p>';
  $output .= theme('item_list', array('items' => $list));
  cache_set($cache_key, $output, 'cache', 300);
  return $output;
}

/**
 * API function to get recent update information for the documentation pages.
 */
function drupalorg_handbook_get_recent_updates($limit = 50) {
  $query = db_select('node', 'n');
  $query->innerJoin('book', 'b', 'n.nid = b.nid');
  $query->innerJoin('node_revision', 'r', 'n.vid = r.vid');
  $query->innerJoin('users', 'u', 'u.uid = r.uid');
  return $query
    ->fields('n', array('nid', 'title', 'changed'))
    ->fields('r', array('log'))
    ->fields('u', array('uid', 'name'))
    ->condition('n.status', 1)
    ->orderBy('n.changed', 'DESC')
    ->range(0, $limit)
    ->execute();
}

/**
 * Implements hook_block_info().
 */
function drupalorg_handbook_block_info() {
  return array(
    'license' => array(
      'info' => t('Handbook License'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
    'meta-sidebar' => array(
      'info' => t('Documentation status'),
      'cache' => DRUPAL_NO_CACHE,
    ),
    'about-page' => array(
      'info' => t('Documentation about'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function drupalorg_handbook_block_view($delta) {
  $section = drupalorg_crosssite_section();
  $node = menu_get_object();
  switch ($delta) {
    case 'license':
      if ($section === 'documentation') {
        return array(
          'subject' => '',
          'content' => t('Drupal’s online documentation is © 2000-!year by the individual contributors and can be used in accordance with the <a href="@ccl_url">Creative Commons License, Attribution-ShareAlike 2.0</a>. PHP code is distributed under the <a href="@gpl_url">GNU General Public License</a>. Comments on documentation pages are used to improve content and then deleted.', array('!year' => date('Y'), '@ccl_url' => url('node/14307'), '@gpl_url' => url('http://www.gnu.org/licenses/old-licenses/gpl-2.0.html'))),
        );
      }
      break;

    case 'meta-sidebar':
      if (($section === 'documentation' || $section === 'community') && isset($node) && isset($node->book['bid'])) {
        $about = drupalorg_handbook_meta_data();
        $links = array();
        if (node_access('update', $node)) {
          $links['edit'] = t('<a href="!url">Edit</a> this page', array('!url' => url('node/' . $node->nid . '/edit')));
        }
        elseif (!user_is_logged_in()) {
          $links['edit'] = l(t('Log in to edit this page'), 'user', array('query' => drupal_get_destination()));
        }
        $report_link = drupalorg_handbook_moderate_link_info($node);
        if (isset($report_link)) {
          $links['report'] = l($report_link['title'], $report_link['href'], array('query' => $report_link['query']));
        }

        return array(
          'subject' => t('Page status'),
          'content' => $about['status'] . '<p>' . implode('<br />', $links) . '</p>',
        );
      }
      break;

    case 'about-page':
      if (($section === 'documentation' || $section === 'community') && isset($node) && isset($node->book['bid'])) {
        $about = drupalorg_handbook_meta_data();
        unset($about['status']);
        if (!empty($about)) {
          return array(
            'subject' => t('About this page'),
            'content' => theme('drupalorg_handbook_meta_sidebar', array('about' => $about)),
          );
        }
      }
      break;
  }
}

/**
 * Implements hook_theme().
 */
function drupalorg_handbook_theme($existing, $type, $theme, $path) {
  return array(
    'drupalorg_handbook_footer_line' => array(
      'variables' => array(),
    ),
    'drupalorg_handbook_contributors' => array(
      'variables' => array(
        'created' => '',
        'updated' => '',
        'contributors' => '',
        'edit_link' => '',
      ),
      'template' => 'handbook-contributors',
    ),
    'drupalorg_handbook_meta_sidebar' => array(
      'variables' => array(
        'about' => array(),
      ),
      'template' => 'handbook-meta-sidebar',
    ),
  );
}

/**
 * Implementation of template_preprocess_drupalorg_home().
 */
function drupalorg_handbook_preprocess_drupalorg_home(&$vars) {
  // Represents the number of results to retrieve. Also utilized for cache field name.
  $count = 5;
  if ($cache = cache_get('drupalorg_handbook_recent_updates_' . $count)) {
    $recent_updates = $cache->data;
  }
  else {
    $result = drupalorg_handbook_get_recent_updates($count);
    $recent_updates = '';
    foreach ($result as $node) {
      $recent_updates .= '<h6>' . l($node->title, 'node/' . $node->nid) . '</h6><p class="submitted">';
      $date = format_date($node->changed);
      $name = theme('username', array('account' => $node));
      $recent_updates .= t('Submitted by !username on !datetime', array('!username' => $name, '!datetime' => $date));
      $recent_updates .= '</p>';
    }
    $recent_updates .= '<p>' . l(t('More documentation…'), 'documentation') . '</p>';
    cache_set('drupalorg_handbook_recent_updates_' . $count, $recent_updates);
  }
  $vars['tab_content_docs'] = $recent_updates;
}

/**
 * Returns HTML for a footer line for a documentation page.
 *
 * @ingroup themeable
 */
function theme_drupalorg_handbook_footer_line() {
  return '<p class="support"><strong>' . t('Looking for support? Visit the !forumlink, or join #drupal-support in !irclink.',
    array(
    '!forumlink' => l(t('Drupal.org forums'), 'forum'),
    '!irclink' => l(t('IRC'), 'node/108355'),
  )) . '</strong></p>';
}

/**
 * Implements hook_form_FORM_ID_alter() for comment_form().
 *
 * Adds a disclaimer if a book node is being commented on.
 */
function drupalorg_handbook_form_comment_form_alter(&$form, $form_state) {
  // Make sure we are on a form to add a new comment (not edit existing),
  // and that the node is a book node.
  if(isset($form['#node']->book['bid']) && !isset($form_state['comment']->cid)) {
    // This is a node in a book. Display disclaimer.
    $form['drupalorg-disclaimer'] = array(
      '#weight' => -2,
      '#markup' => '<p>' . t('Note:') . '</p>' .
      '<ul>' .
      '<li>' . t('Is your comment an addition, problem report, or example? Instead of adding a comment, edit the page content directly. Or, if you are unsure of the correct edits, add a comment here, and then edit the page to update the page status. Be aware that comments are removed after page edits are made.') . '</li>' .
      '<li>' . t('Is your comment a question or request for support? Take it to the <a href="!forums">forums</a>. Questions are not answered here, and comments not providing useful information are removed.', array('!forums' => url('forum'))) . '</li>' .
      '</ul>',
    );
  }
}
