<?php

/**
 * @file
 * Code for the Drupalorg redesign 2018 feature.
 */

include_once 'drupalorg_redesign_2018.features.inc';

/**
 * Implements hook_preprocess_html().
 */
function drupalorg_redesign_2018_preprocess_html(&$variables) {
  $module_path = drupal_get_path('module', 'drupalorg_redesign_2018');
  drupal_add_js($module_path . '/js/libraries.min.js');
  drupal_add_js($module_path . '/js/redesign.js');
}

/**
 * Implements hook_preprocess_entity().
 */
function drupalorg_redesign_2018_preprocess_entity(&$variables) {
  if ($variables['entity_type'] === 'field_collection_item') {
    if ($variables['elements']['#bundle'] === 'field_infographics') {
      if (isset($variables['content']['field_cta_graphic'][0])) {
        $dir   = drupal_get_path('module', 'drupalorg_redesign_2018') . '/shapes/';
        $files = preg_grep('/^([^.])/', scandir($dir));
        $count = count($files);
        $int   = rand(1, $count);

        $variables['content']['field_cta_graphic'][0]['#prefix'] = format_string('<div class="field-prefix-shape">!field_content</div>', [
          '!field_content' => file_get_contents($dir . '/random-shape' . $int . '.svg'),
        ]);
      }

      if (isset($variables['field_collection_item']->field_link[LANGUAGE_NONE][0]['url'])) {
        $variables['classes_array'][] = 'h-animate';
        $variables['content']['field_title'][0]['#markup'] = l(html_entity_decode($variables['content']['field_title'][0]['#markup']), $variables['field_collection_item']->field_link[LANGUAGE_NONE][0]['url']);
      }
    }
  }
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function drupalorg_redesign_2018_preprocess_views_view_field(&$variables) {
  // Strip tags for the case studies homepage view.
  if ($variables['view']->name === 'redesign_2018_case_studies') {
    if ($variables['view']->current_display === 'panel_pane_1') {
      if (isset($variables['field']->real_field) and $variables['field']->real_field === 'body_value') {
        $variables['output'] = format_string('<p>@text</p>', array(
          '@text' => strip_tags($variables['output']),
        ));
      }
    }
  }
}

/**
 * Implements hook_preprocess_panels_pane().
 */
function drupalorg_redesign_2018_preprocess_panels_pane(&$variables) {
  if (is_array($variables['content'])) {
    if (isset($variables['content']['title']['#value'])) {
      $variables['content']['title']['#value'] = html_entity_decode($variables['content']['title']['#value']);
    }
  }

  // Redesign 2018.
  if (in_array('d-hero', $variables['classes_array'])) {
    $variables['theme_hook_suggestions'][] = 'panels_pane__d_hero';
  }

  foreach ($variables['classes_array'] as $key => $value) {
    $exploded = explode(' ', $value);
    if (in_array('d-persona', $exploded)) {
      $variables['theme_hook_suggestions'][] = 'panels_pane__d_persona';
      preg_match('/d-persona-[\S]*/', $value, $matches);
      $variables['pane_graphic_svg'] = '';
      if (isset($matches[0])) {
        $file_path = drupal_get_path('theme', 'bluecheese') . '/images/personas/' . $matches[0] . '.svg';

        $variables['pane_graphic_svg'] = file_get_contents($file_path);
      }
    }
  }

}
