<?php

/**
 * @file
 * Code for the Drupalorg redesign 2018 feature.
 */

include_once 'drupalorg_redesign_2018.features.inc';

/**
 * Implements hook_preprocess_entity().
 */
function drupalorg_redesign_2018_preprocess_entity(&$variables) {
  if ($variables['entity_type'] === 'field_collection_item') {
    if ($variables['elements']['#bundle'] === 'field_infographics') {
      if (isset($variables['content']['field_cta_graphic'][0])) {
        $dir   = drupal_get_path('module', 'drupalorg_redesign_2018') . '/shapes/';
        $scan  = scandir($dir);
        $count = count($scan) - 2;
        $int   = rand(1, $count);

        $variables['content']['field_cta_graphic'][0]['#prefix'] = format_string('<div class="field-prefix-shape">!field_content</div>', [
          '!field_content' => file_get_contents($dir . '/random-shape' . $int . '.svg'),
        ]);
      }

      if (isset($variables['field_collection_item']->field_link[LANGUAGE_NONE][0]['url'])) {
        $variables['classes_array'][] = 'h-animate';
        $variables['content']['field_title'][0]['#markup'] = l($variables['content']['field_title'][0]['#markup'], $variables['field_collection_item']->field_link[LANGUAGE_NONE][0]['url']);
      }
    }
  }
}
