<?php

/**
 * Implements hook_block_info().
 */
function drupalorg_order_facet_block_info() {
  return array(
    'ds_created' => array(
      'info' => t('New content'),
      'direction' => 'desc',
      'cache' => DRUPAL_NO_CACHE,
    ),
    'iss_project_release_usage' => array(
      'info' => t('Most installed'),
      'direction' => 'desc',
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function drupalorg_order_facet_block_view($delta = '') {
  $env_id = apachesolr_default_environment();
  if (apachesolr_has_searched($env_id) && ($query = apachesolr_current_query($env_id))) {
    $blocks = drupalorg_order_facet_block_info();
    // Replace 'content' with 'Modules', 'Themes', etc.
    foreach ($query->getFilters() as $filter) {
      if ($filter['#name'] === 'im_vid_3') {
        $term = taxonomy_get_term($filter['#value']);
        $blocks[$delta]['info'] = str_replace('content', check_plain($term->name), $blocks[$delta]['info']);
      }
    }
    $results = drupalorg_order_facet_build($delta, $blocks[$delta], $query);
    if (!empty($results)) {
      return array(
        'subject' => $blocks[$delta]['info'],
        'content' => $results,
      );
    }
  }
}

/**
 * Generate an order facet.
 */
function drupalorg_order_facet_build($sort, $info, $query, $more = TRUE) {
  // Generate a new query based on the executed one.
  $order_query = clone $query;
  $order_query->setSolrSort($sort, $info['direction']);

  // Retrieve the query values first so everything is formatted correctly,
  // and we only have relevant values in the url.
  $query_values = $order_query->getSolrsortUrlQuery();
  foreach ($order_query->getFilters() as $filter) {
    $query_values['f'][] = $filter['#name'] . ':' . $filter['#value'];
  }

  // Execute the Solr query.
  $order_query->addParams(array(
    'fl' => 'id,nid,title,url',
    'start' => 0,
    'rows' => 4,
  ));
  $response = $order_query->search();

  $items = array();
  if ($response->response->numFound > 0) {
    foreach ($response->response->docs as $doc) {
      $items[] = l($doc->label, $doc->url);
    }
  }

  if ($items && $more) {
    // Add the "more" link.
    $items[] = array(
      'data' => l(t('More @title', array('@title' => $info['info'])), $order_query->getPath(), array('query' => $query_values)),
      'class' => 'all',
    );
  }
  return theme('item_list', array('items' => $items, 'attributes' => array('class' => 'flat')));
}
